# Generated by Django 4.2.20 on 2025-03-15 13:45

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_bai_hat', models.CharField(max_length=200)),
                ('ma_album', models.CharField(blank=True, max_length=50, null=True)),
                ('trang_thai', models.IntegerField(default=1)),
                ('hinh_anh', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('luot_nghe', models.IntegerField(default=0)),
                ('ngay_phat_hanh', models.DateField()),
                ('ma_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
