# Generated by Django 5.1.7 on 2025-04-01 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='ma_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritesong',
            name='ma_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='ma_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='ma_playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='songs.playlist'),
        ),
        migrations.AddField(
            model_name='song',
            name='ma_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='songs.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='ma_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='ma_bai_hat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='songs.song'),
        ),
        migrations.AddField(
            model_name='favoritesong',
            name='ma_bai_hat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='songs.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='ma_the_loai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='songs.theloai'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistsong',
            unique_together={('ma_playlist', 'ma_bai_hat')},
        ),
        migrations.AlterUniqueTogether(
            name='favoritesong',
            unique_together={('ma_user', 'ma_bai_hat')},
        ),
    ]
