# Generated by Django 4.2.20 on 2025-03-15 17:28

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0002_song_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('ma_album', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ten_album', models.CharField(max_length=200)),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('hinh_anh', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('trang_thai', models.IntegerField(default=1)),
                ('ma_tac_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
