# Generated by Django 4.2.20 on 2025-03-15 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='ma_tac_gia',
            new_name='ma_user',
        ),
        migrations.AlterField(
            model_name='song',
            name='ngay_phat_hanh',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
