# Generated by Django 4.2.20 on 2025-03-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_rename_ma_tac_gia_album_ma_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='ma_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='songs.album'),
        ),
    ]
