# Generated by Django 4.2.20 on 2025-03-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_song_ma_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='albums/images/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='songs/audio/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='songs/images/'),
        ),
    ]
