# Generated by Django 4.2.20 on 2025-03-19 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0006_alter_album_hinh_anh_alter_song_audio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('ma_playlist', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ten_playlist', models.CharField(max_length=200)),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='playlists/images/')),
                ('ma_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_bai_hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='songs.song')),
                ('ma_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='songs.playlist')),
            ],
            options={
                'unique_together': {('ma_playlist', 'ma_bai_hat')},
            },
        ),
    ]
