# Generated by Django 4.2.20 on 2025-03-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_theloai_song_ma_the_loai'),
    ]

    operations = [
        migrations.AddField(
            model_name='theloai',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
