# Generated by Django 4.2.20 on 2025-03-24 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0009_theloai_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_bai_hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='songs.song')),
                ('ma_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ma_user', 'ma_bai_hat')},
            },
        ),
    ]
