# Generated by Django 4.2 on 2025-05-03 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('ma_album', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ten_album', models.CharField(max_length=200)),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='albums/images/')),
                ('trang_thai', models.IntegerField(default=1)),
                ('ma_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('ma_playlist', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ten_playlist', models.CharField(max_length=200)),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='playlists/images/')),
                ('ma_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_the_loai', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='the_loai/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_bai_hat', models.CharField(max_length=200)),
                ('trang_thai', models.IntegerField(default=1)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='songs/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='songs/video/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='songs/audio/')),
                ('luot_nghe', models.IntegerField(default=0)),
                ('ngay_phat_hanh', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_premium', models.BooleanField(default=False)),
                ('ma_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='songs.album')),
                ('ma_the_loai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='songs.theloai')),
                ('ma_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_bai_hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='songs.song')),
                ('ma_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='songs.playlist')),
            ],
            options={
                'unique_together': {('ma_playlist', 'ma_bai_hat')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_bai_hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='songs.song')),
                ('ma_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ma_user', 'ma_bai_hat')},
            },
        ),
    ]
