# Generated by Django 4.2 on 2025-04-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

   

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
