# Generated by Django 4.2.20 on 2025-04-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('ma_premium', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ten_premium', models.CharField(max_length=200)),
                ('thoi_han', models.IntegerField(default=0)),
                ('gia_ban', models.FloatField(default=0)),
                ('mo_ta', models.CharField(max_length=50)),
                ('trang_thai', models.IntegerField(default=1)),
            ],
        ),
    ]
