# Generated by Django 4.2.20 on 2025-05-02 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('ma_premium', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ten_premium', models.CharField(max_length=200)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('thoi_han', models.IntegerField(default=0)),
                ('gia_ban', models.FloatField(default=0)),
                ('trang_thai', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('callback_sent', models.BooleanField(default=False)),
                ('ma_premium', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ten_premium', models.CharField(max_length=200)),
                ('thoi_han', models.IntegerField(default=0)),
                ('gia_ban', models.FloatField(default=0)),
                ('mo_ta', models.CharField(max_length=50)),
                ('trang_thai', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='premium.premium')),
            ],
        ),
    ]
