# Generated by Django 4.2 on 2025-04-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0003_alter_subscription_options_remove_premium_mo_ta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premium',
            options={'verbose_name': 'Gói Premium', 'verbose_name_plural': 'Gói Premium'},
        ),
        migrations.RemoveField(
            model_name='premium',
            name='gia_ban',
        ),
        migrations.AddField(
            model_name='premium',
            name='gia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá'),
        ),
        migrations.AddField(
            model_name='premium',
            name='mo_ta',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='ma_premium',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Mã gói'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='ten_premium',
            field=models.CharField(max_length=100, verbose_name='Tên gói'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='thoi_han',
            field=models.IntegerField(verbose_name='Thời hạn (ngày)'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='trang_thai',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
    ]
