# Generated by Django 4.2 on 2025-04-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0004_alter_premium_options_remove_premium_gia_ban_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premium',
            options={},
        ),
        migrations.RemoveField(
            model_name='premium',
            name='gia',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='mo_ta',
        ),
        migrations.AddField(
            model_name='premium',
            name='gia_ban',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='ma_premium',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='ten_premium',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='premium',
            name='thoi_han',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premium',
            name='trang_thai',
            field=models.IntegerField(default=1),
        ),
    ]
