# Generated by Django 4.2 on 2025-04-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0005_alter_premium_options_remove_premium_gia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='mo_ta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
