# Generated by Django 4.2 on 2025-04-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0006_premium_mo_ta'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpayment',
            name='callback_sent',
            field=models.BooleanField(default=False),
        ),
    ]
