# Generated by Django 4.2 on 2025-04-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalopay', '0003_premiumpackage_premiumpayment_subscriptionhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpackage',
            name='code',
            field=models.CharField(default='DEFAULT', max_length=20, unique=True),
        ),
    ]
