# Generated by Django 4.2 on 2025-04-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zalopay', '0004_premiumpackage_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumpayment',
            name='package',
        ),
        migrations.RemoveField(
            model_name='premiumpayment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='package',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='PremiumPackage',
        ),
        migrations.DeleteModel(
            name='PremiumPayment',
        ),
        migrations.DeleteModel(
            name='SubscriptionHistory',
        ),
    ]
