# Generated by Django 4.2.20 on 2025-03-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phanquyen',
            name='ten_quyen',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
